language: python
python: 
  - 3.6
cache: pip
services:
  - mysql
env:
  - DJANGO=1.11 DB=mysql
install:
  - pip install -r requirements.txt
before_script:
  - echo "USE mysql;\nUPDATE user SET password=PASSWORD('Up123pU') WHERE user='root';\nFLUSH PRIVILEGES;\n" | mysql -u root
script:
  - pytest
  - python manage.py test