# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-05-02 18:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_post_updated_on'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'permissions': (('view_all_posts', 'View all the posts'),)},
        ),
    ]
